In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv("train_cleaned.csv")

print(df.shape)

(1458, 86)

In [49]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 86 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1458 non-null   int64
 1   MSSubClass     1458 non-null   float64
 2   MSZoning       1458 non-null   str
 3   LotFrontage    1458 non-null   float64
 4   LotArea        1458 non-null   float64
 5   Street         1458 non-null   str
 6   LotShape       1458 non-null   str
 7   LandContour    1458 non-null   str
 8   Utilities      1458 non-null   str
 9   LotConfig      1458 non-null   str
 10  LandSlope      1458 non-null   str
 11  Neighborhood   1458 non-null   str
 12  Condition1     1458 non-null   str
 13  Condition2     1458 non-null   str
 14  BldgType       1458 non-null   str
 15  HouseStyle     1458 non-null   str
 16  OverallQual    1458 non-null   int64
 17  OverallCond    1458 non-null   int64
 18  YearBuilt      1458 non-null   int64
 19  YearRemodAdd   1458 non-null   int64
 20  RoofStyle      1458 non-null   str
 21  RoofMatl       1458 non-null   str
 22  Exterior1st    1458 non-null   str
 23  Exterior2nd    1458 non-null   str
 24  MasVnrArea     1458 non-null   float64
 25  ExterQual      1458 non-null   str
 26  ExterCond      1458 non-null   str
 27  Foundation     1458 non-null   str
 28  BsmtQual       1421 non-null   str
 29  BsmtCond       1421 non-null   str
 30  BsmtExposure   1420 non-null   str
 31  BsmtFinType1   1421 non-null   str
 32  BsmtFinSF1     1458 non-null   float64
 33  BsmtFinType2   1420 non-null   str
 34  BsmtFinSF2     1458 non-null   float64
 35  BsmtUnfSF      1458 non-null   float64
 36  TotalBsmtSF    1458 non-null   int64
 37  Heating        1458 non-null   str
 38  HeatingQC      1458 non-null   str
 39  CentralAir     1458 non-null   str
 40  Electrical     1457 non-null   str
 41  1stFlrSF       1458 non-null   float64
 42  2ndFlrSF       1458 non-null   float64
 43  LowQualFinSF   1458 non-null   float64
 44  GrLivArea      1458 non-null   float64
 45  BsmtFullBath   1458 non-null   int64
 46  BsmtHalfBath   1458 non-null   float64
 47  FullBath       1458 non-null   int64
 48  HalfBath       1458 non-null   int64
 49  BedroomAbvGr   1458 non-null   int64
 50  KitchenAbvGr   1458 non-null   float64
 51  KitchenQual    1458 non-null   str
 52  TotRmsAbvGrd   1458 non-null   int64
 53  Functional     1458 non-null   str
 54  Fireplaces     1458 non-null   int64
 55  FireplaceQu    768 non-null    str
 56  GarageType     1377 non-null   str
 57  GarageYrBlt    1458 non-null   float64
 58  GarageFinish   1377 non-null   str
 59  GarageCars     1458 non-null   int64
 60  GarageArea     1458 non-null   int64
 61  GarageQual     1377 non-null   str
 62  GarageCond     1377 non-null   str
 63  PavedDrive     1458 non-null   str
 64  WoodDeckSF     1458 non-null   float64
 65  OpenPorchSF    1458 non-null   float64
 66  EnclosedPorch  1458 non-null   float64
 67  3SsnPorch      1458 non-null   float64
 68  ScreenPorch    1458 non-null   float64
 69  PoolArea       1458 non-null   float64
 70  MiscVal        1458 non-null   float64
 71  MoSold         1458 non-null   int64
 72  YrSold         1458 non-null   int64
 73  SaleType       1458 non-null   str
 74  SaleCondition  1458 non-null   str
 75  SalePrice      1458 non-null   int64
 76  TotalSF        1458 non-null   float64
 77  HouseAge       1458 non-null   int64
 78  RemodAge       1458 non-null   int64
 79  TotalBath      1458 non-null   float64
 80  TotalPorchSF   1458 non-null   float64
 81  HasPool        1458 non-null   float64
 82  HasGarage      1458 non-null   float64
 83  HasFireplace   1458 non-null   int64
 84  HasBsmt        1458 non-null   float64
 85  Has2ndFlr      1458 non-null   int64
dtypes: float64(27), int64(21), str(38)
memory usage: 979.7 KB
None

In [50]:
df.set_index("Id", inplace=True)
df.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,TotalSF,HouseAge,RemodAge,TotalBath,TotalPorchSF,HasPool,HasGarage,HasFireplace,HasBsmt,Has2ndFlr
count,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,...,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000
mean,3.818393,4.212945,9.108606,6.093964,5.576132,1971.218107,1984.834019,2.114038,4.224311,0.656297,...,7.801013,36.598080,22.982167,2.207476,3.108108,0.002852,0.654639,0.526749,0.675557,0.431413
std,0.688741,0.311546,0.513705,1.376369,1.113359,30.193754,20.641760,2.625175,2.990471,1.846151,...,0.309429,30.240565,20.636501,0.781341,2.210934,0.044389,0.158828,0.499455,0.109047,0.495443
min,3.044522,3.091042,7.170888,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,5.814131,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.044522,4.110874,8.928706,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,7.605641,8.000000,4.000000,2.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000
50%,3.931826,4.248495,9.156518,6.000000,5.000000,1972.500000,1994.000000,0.000000,5.948032,0.000000,...,7.813592,35.000000,14.000000,2.000000,3.891820,0.000000,0.693147,1.000000,0.693147,0.000000
75%,4.262680,4.382027,9.358847,7.000000,6.000000,2000.000000,2004.000000,5.104426,6.568075,0.000000,...,8.007450,54.000000,41.000000,2.500000,4.918149,0.000000,0.693147,1.000000,0.693147,1.000000
max,5.252273,5.749393,12.279537,10.000000,9.000000,2010.000000,2010.000000,7.378384,7.691200,7.296413,...,8.835356,136.000000,60.000000,6.000000,6.935370,0.693147,0.693147,1.000000,0.693147,1.000000

In [51]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'TotalSF', 'HouseAge', 'RemodAge',
       'TotalBath', 'TotalPorchSF', 'HasPool', 'HasGarage', 'HasFireplace',
       'HasBsmt', 'Has2ndFlr'],
      dtype='str')

### Models

- Simple Models to show improvement from
    - Linear Regression
    - Polynomial Regression

- Advanced Models
    - Random Forests (general good performance, bagging)
    - XGBoost (general good performance, boosting)
    - Lasso Regression (subset selection)
    - PCR (for isolating features)

In [106]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from sklearn.pipeline import Pipeline

In [53]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'str']).columns.tolist()

print(numerical_cols)
print(categorical_cols)

['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice', 'TotalSF', 'HouseAge', 'RemodAge', 'TotalBath', 'TotalPorchSF', 'HasPool', 'HasGarage', 'HasFireplace', 'HasBsmt', 'Has2ndFlr']
['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']

In [54]:
le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [55]:
x = df.drop(columns=["SalePrice"])
y = df["SalePrice"]

In [56]:
for col in x.columns:
    if (col == "SalePrice"):
        print("Drop Failed")
        break

In [57]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [58]:
x.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,TotalSF,HouseAge,RemodAge,TotalBath,TotalPorchSF,HasPool,HasGarage,HasFireplace,HasBsmt,Has2ndFlr
Id,,,,,,,,,,,,,,,,,,,,,
1,4.110874,3,4.189655,9.042040,1,3,3,0,4,0,...,7.850493,5,5,3.5,4.127134,0.0,0.693147,0,0.693147,1
2,3.044522,3,4.394449,9.169623,1,3,3,0,2,0,...,7.833996,31,31,2.5,0.000000,0.0,0.693147,1,0.693147,0
3,4.110874,3,4.234107,9.328212,1,0,3,0,4,0,...,7.903596,7,6,3.5,3.761200,0.0,0.693147,1,0.693147,1
4,4.262680,3,4.110874,9.164401,1,0,3,0,0,0,...,7.813592,91,36,2.0,5.730100,0.0,0.693147,1,0.693147,1
5,4.110874,3,4.442651,9.565284,1,0,3,0,2,0,...,8.114923,8,8,3.5,4.442651,0.0,0.693147,1,0.693147,1

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=434)
sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train = sc.fit_transform(x_train)

In [111]:
def create_metrics(mae, rmse, mape, r2):
    adjr2 = 1 - (1 - r2) * (x.shape[0] - 1) / (x.shape[0] - x.shape[1] - 1)

    data = {
        "Metrics": ["Mean Absolute Error", "Root Mean Squared Error", "Mean Absolute Percentage Error", "R Squared", "Adjusted R Squared"],
        "Values": [round(mae, 2), round(rmse, 2), round(mape, 2), round(r2, 2), round(adjr2, 2)],
        "Explanation" : ["Pure error", "Penalizes big misses", "More intepretable MAE", "Overall fit", "Useful for subset selecting models"]  
            }
    
    metrics = pd.DataFrame(data)

    return metrics

In [112]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Linear Regression:")
metrics.head()

Linear Regression:

,Metrics,Values,Explanation
0,Mean Absolute Error,20187.09,Pure error
1,Root Mean Squared Error,27082.07,Penalizes big misses
2,Mean Absolute Percentage Error,0.13,More intepretable MAE
3,R Squared,0.88,Overall fit
4,Adjusted R Squared,0.87,Useful for subset selecting models

In [113]:
pipeline2 = Pipeline([
    ('poly', PolynomialFeatures(degree = 2)),
    ('model', LinearRegression())
])

pipeline2.fit(x_train, y_train)

y_pred = pipeline2.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Polynomial Regression (Degree = 2):")
metrics.head()

Polynomial Regression (Degree = 2):

,Metrics,Values,Explanation
0,Mean Absolute Error,39022.03,Pure error
1,Root Mean Squared Error,53016.30,Penalizes big misses
2,Mean Absolute Percentage Error,0.27,More intepretable MAE
3,R Squared,0.53,Overall fit
4,Adjusted R Squared,0.50,Useful for subset selecting models

In [114]:
pipeline3 = Pipeline([
    ('poly', PolynomialFeatures(degree = 3)),
    ('model', LinearRegression())
])

pipeline3.fit(x_train, y_train)

y_pred = pipeline3.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Polynomial Regression (Degree = 3):")
metrics.head()

Polynomial Regression (Degree = 3):

,Metrics,Values,Explanation
0,Mean Absolute Error,19959.86,Pure error
1,Root Mean Squared Error,29555.46,Penalizes big misses
2,Mean Absolute Percentage Error,0.14,More intepretable MAE
3,R Squared,0.85,Overall fit
4,Adjusted R Squared,0.84,Useful for subset selecting models