In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train_cleaned.csv")

print(df.shape)

(1458, 86)

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 86 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1458 non-null   int64
 1   MSSubClass     1458 non-null   float64
 2   MSZoning       1458 non-null   str
 3   LotFrontage    1458 non-null   float64
 4   LotArea        1458 non-null   float64
 5   Street         1458 non-null   str
 6   LotShape       1458 non-null   str
 7   LandContour    1458 non-null   str
 8   Utilities      1458 non-null   str
 9   LotConfig      1458 non-null   str
 10  LandSlope      1458 non-null   str
 11  Neighborhood   1458 non-null   str
 12  Condition1     1458 non-null   str
 13  Condition2     1458 non-null   str
 14  BldgType       1458 non-null   str
 15  HouseStyle     1458 non-null   str
 16  OverallQual    1458 non-null   int64
 17  OverallCond    1458 non-null   int64
 18  YearBuilt      1458 non-null   int64
 19  YearRemodAdd   1458 non-null   int64
 20  RoofStyle      1458 non-null   str
 21  RoofMatl       1458 non-null   str
 22  Exterior1st    1458 non-null   str
 23  Exterior2nd    1458 non-null   str
 24  MasVnrArea     1458 non-null   float64
 25  ExterQual      1458 non-null   str
 26  ExterCond      1458 non-null   str
 27  Foundation     1458 non-null   str
 28  BsmtQual       1421 non-null   str
 29  BsmtCond       1421 non-null   str
 30  BsmtExposure   1420 non-null   str
 31  BsmtFinType1   1421 non-null   str
 32  BsmtFinSF1     1458 non-null   float64
 33  BsmtFinType2   1420 non-null   str
 34  BsmtFinSF2     1458 non-null   float64
 35  BsmtUnfSF      1458 non-null   float64
 36  TotalBsmtSF    1458 non-null   int64
 37  Heating        1458 non-null   str
 38  HeatingQC      1458 non-null   str
 39  CentralAir     1458 non-null   str
 40  Electrical     1457 non-null   str
 41  1stFlrSF       1458 non-null   float64
 42  2ndFlrSF       1458 non-null   float64
 43  LowQualFinSF   1458 non-null   float64
 44  GrLivArea      1458 non-null   float64
 45  BsmtFullBath   1458 non-null   int64
 46  BsmtHalfBath   1458 non-null   float64
 47  FullBath       1458 non-null   int64
 48  HalfBath       1458 non-null   int64
 49  BedroomAbvGr   1458 non-null   int64
 50  KitchenAbvGr   1458 non-null   float64
 51  KitchenQual    1458 non-null   str
 52  TotRmsAbvGrd   1458 non-null   int64
 53  Functional     1458 non-null   str
 54  Fireplaces     1458 non-null   int64
 55  FireplaceQu    768 non-null    str
 56  GarageType     1377 non-null   str
 57  GarageYrBlt    1458 non-null   float64
 58  GarageFinish   1377 non-null   str
 59  GarageCars     1458 non-null   int64
 60  GarageArea     1458 non-null   int64
 61  GarageQual     1377 non-null   str
 62  GarageCond     1377 non-null   str
 63  PavedDrive     1458 non-null   str
 64  WoodDeckSF     1458 non-null   float64
 65  OpenPorchSF    1458 non-null   float64
 66  EnclosedPorch  1458 non-null   float64
 67  3SsnPorch      1458 non-null   float64
 68  ScreenPorch    1458 non-null   float64
 69  PoolArea       1458 non-null   float64
 70  MiscVal        1458 non-null   float64
 71  MoSold         1458 non-null   int64
 72  YrSold         1458 non-null   int64
 73  SaleType       1458 non-null   str
 74  SaleCondition  1458 non-null   str
 75  SalePrice      1458 non-null   int64
 76  TotalSF        1458 non-null   float64
 77  HouseAge       1458 non-null   int64
 78  RemodAge       1458 non-null   int64
 79  TotalBath      1458 non-null   float64
 80  TotalPorchSF   1458 non-null   float64
 81  HasPool        1458 non-null   float64
 82  HasGarage      1458 non-null   float64
 83  HasFireplace   1458 non-null   int64
 84  HasBsmt        1458 non-null   float64
 85  Has2ndFlr      1458 non-null   int64
dtypes: float64(27), int64(21), str(38)
memory usage: 979.7 KB
None

In [4]:
df.set_index("Id", inplace=True)
df.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,TotalSF,HouseAge,RemodAge,TotalBath,TotalPorchSF,HasPool,HasGarage,HasFireplace,HasBsmt,Has2ndFlr
count,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,...,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000,1458.000000
mean,3.818393,4.212945,9.108606,6.093964,5.576132,1971.218107,1984.834019,2.114038,4.224311,0.656297,...,7.801013,36.598080,22.982167,2.207476,3.108108,0.002852,0.654639,0.526749,0.675557,0.431413
std,0.688741,0.311546,0.513705,1.376369,1.113359,30.193754,20.641760,2.625175,2.990471,1.846151,...,0.309429,30.240565,20.636501,0.781341,2.210934,0.044389,0.158828,0.499455,0.109047,0.495443
min,3.044522,3.091042,7.170888,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,5.814131,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.044522,4.110874,8.928706,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,7.605641,8.000000,4.000000,2.000000,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000
50%,3.931826,4.248495,9.156518,6.000000,5.000000,1972.500000,1994.000000,0.000000,5.948032,0.000000,...,7.813592,35.000000,14.000000,2.000000,3.891820,0.000000,0.693147,1.000000,0.693147,0.000000
75%,4.262680,4.382027,9.358847,7.000000,6.000000,2000.000000,2004.000000,5.104426,6.568075,0.000000,...,8.007450,54.000000,41.000000,2.500000,4.918149,0.000000,0.693147,1.000000,0.693147,1.000000
max,5.252273,5.749393,12.279537,10.000000,9.000000,2010.000000,2010.000000,7.378384,7.691200,7.296413,...,8.835356,136.000000,60.000000,6.000000,6.935370,0.693147,0.693147,1.000000,0.693147,1.000000

In [5]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'TotalSF', 'HouseAge', 'RemodAge',
       'TotalBath', 'TotalPorchSF', 'HasPool', 'HasGarage', 'HasFireplace',
       'HasBsmt', 'Has2ndFlr'],
      dtype='str')

### Models

- Simple Models to show improvement from
    - Linear Regression
    - Polynomial Regression

- Advanced Models
    - Random Forests (general good performance, bagging)
    - XGBoost (general good performance, boosting)
    - Lasso Regression (subset selection)
    - PCR (for isolating features)

In [6]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

In [7]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'str']).columns.tolist()

print(numerical_cols)
print(categorical_cols)

['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice', 'TotalSF', 'HouseAge', 'RemodAge', 'TotalBath', 'TotalPorchSF', 'HasPool', 'HasGarage', 'HasFireplace', 'HasBsmt', 'Has2ndFlr']
['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType', 'SaleCondition']

In [8]:
#le = LabelEncoder()

#for col in categorical_cols:
#    df[col] = le.fit_transform(df[col])

In [9]:
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [10]:
df.shape

(1458, 243)

In [11]:
x = df.drop(columns=["SalePrice"])
y = df["SalePrice"]

In [12]:
for col in x.columns:
    if (col == "SalePrice"):
        print("Drop Failed")
        break

In [13]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [14]:
x.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,,,,,,,,,,,,,,,,,,,,,
1,4.110874,4.189655,9.042040,7,5,2003,2003,5.283204,6.561031,0.0,...,False,False,False,False,True,False,False,False,True,False
2,3.044522,4.394449,9.169623,6,8,1976,1976,0.000000,6.886532,0.0,...,False,False,False,False,True,False,False,False,True,False
3,4.110874,4.234107,9.328212,7,5,2001,2002,5.093750,6.188264,0.0,...,False,False,False,False,True,False,False,False,True,False
4,4.262680,4.110874,9.164401,7,5,1915,1970,0.000000,5.379897,0.0,...,False,False,False,False,True,False,False,False,False,False
5,4.110874,4.442651,9.565284,8,5,2000,2000,5.860786,6.486161,0.0,...,False,False,False,False,True,False,False,False,True,False

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 1458 entries, 1 to 1460
Columns: 243 entries, MSSubClass to SaleCondition_Partial
dtypes: bool(196), float64(27), int64(20)
memory usage: 825.8 KB

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=434)
sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train = sc.fit_transform(x_train)

In [16]:
def create_metrics(mae, rmse, mape, r2):
    adjr2 = 1 - (1 - r2) * (x.shape[0] - 1) / (x.shape[0] - x.shape[1] - 1)

    data = {
        "Metrics": ["Mean Absolute Error", "Root Mean Squared Error", "Mean Absolute Percentage Error", "R Squared", "Adjusted R Squared"],
        "Values": [round(mae, 2), round(rmse, 2), round(mape, 2), round(r2, 2), round(adjr2, 2)],
        "Explanation" : ["Pure error", "Penalizes big misses", "More intepretable MAE", "Overall fit", "Useful for subset selecting models"]  
            }
    
    metrics = pd.DataFrame(data)

    return metrics

In [17]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Linear Regression:")
metrics.head()

Linear Regression:

,Metrics,Values,Explanation
0,Mean Absolute Error,18853.25,Pure error
1,Root Mean Squared Error,25376.87,Penalizes big misses
2,Mean Absolute Percentage Error,0.12,More intepretable MAE
3,R Squared,0.89,Overall fit
4,Adjusted R Squared,0.87,Useful for subset selecting models

In [18]:
pipeline2 = Pipeline([
    ('poly', PolynomialFeatures(degree = 2)),
    ('model', LinearRegression())
])

pipeline2.fit(x_train, y_train)

y_pred = pipeline2.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Polynomial Regression (Degree = 2):")
metrics.head()

Polynomial Regression (Degree = 2):

,Metrics,Values,Explanation
0,Mean Absolute Error,26177.50,Pure error
1,Root Mean Squared Error,36003.04,Penalizes big misses
2,Mean Absolute Percentage Error,0.18,More intepretable MAE
3,R Squared,0.78,Overall fit
4,Adjusted R Squared,0.74,Useful for subset selecting models

In [20]:
pipeline3 = Pipeline([
    ('poly', PolynomialFeatures(degree = 3)),
    ('model', LinearRegression())
])

pipeline3.fit(x_train, y_train)

y_pred = pipeline3.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print("Polynomial Regression (Degree = 3):")
metrics.head()

MemoryError: Unable to allocate 19.7 GiB for an array with shape (1093, 2421090) and data type float64

In [19]:
from sklearn.linear_model import LassoCV

model = LassoCV(cv=5, random_state=434, max_iter=10000).fit(x_train, y_train)

y_pred = model.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print(f"Lasso Regression with an regularization parameter of {model.alpha_:.2f}")
metrics.head()

Lasso Regression with an regularization parameter of 482.15

,Metrics,Values,Explanation
0,Mean Absolute Error,16382.78,Pure error
1,Root Mean Squared Error,23181.12,Penalizes big misses
2,Mean Absolute Percentage Error,0.10,More intepretable MAE
3,R Squared,0.91,Overall fit
4,Adjusted R Squared,0.89,Useful for subset selecting models

In [20]:
ctr = 0
total = 0
dropped = []
for coef in model.coef_:
    if coef == 0:
        total = total + 1
        print(f"Feature {ctr} ({x.columns[ctr]}) set to 0")
        dropped.append(x.columns[ctr])
    ctr = ctr + 1

print(f"A total of {total} features were set to 0")

Feature 7 (MasVnrArea) set to 0
Feature 12 (1stFlrSF) set to 0
Feature 16 (BsmtFullBath) set to 0
Feature 17 (BsmtHalfBath) set to 0
Feature 28 (OpenPorchSF) set to 0
Feature 29 (EnclosedPorch) set to 0
Feature 33 (MiscVal) set to 0
Feature 35 (YrSold) set to 0
Feature 36 (TotalSF) set to 0
Feature 37 (HouseAge) set to 0
Feature 38 (RemodAge) set to 0
Feature 40 (TotalPorchSF) set to 0
Feature 41 (HasPool) set to 0
Feature 43 (HasFireplace) set to 0
Feature 45 (Has2ndFlr) set to 0
Feature 47 (MSZoning_RH) set to 0
Feature 48 (MSZoning_RL) set to 0
Feature 49 (MSZoning_RM) set to 0
Feature 53 (LotShape_Reg) set to 0
Feature 56 (LandContour_Lvl) set to 0
Feature 61 (LotConfig_Inside) set to 0
Feature 63 (LandSlope_Sev) set to 0
Feature 64 (Neighborhood_Blueste) set to 0
Feature 65 (Neighborhood_BrDale) set to 0
Feature 68 (Neighborhood_CollgCr) set to 0
Feature 82 (Neighborhood_Sawyer) set to 0
Feature 86 (Neighborhood_Timber) set to 0
Feature 87 (Neighborhood_Veenker) set to 0
Feature 88 (Condition1_Feedr) set to 0
Feature 90 (Condition1_PosA) set to 0
Feature 93 (Condition1_RRAn) set to 0
Feature 94 (Condition1_RRNe) set to 0
Feature 95 (Condition1_RRNn) set to 0
Feature 96 (Condition2_Feedr) set to 0
Feature 97 (Condition2_Norm) set to 0
Feature 101 (Condition2_RRAn) set to 0
Feature 102 (Condition2_RRNn) set to 0
Feature 103 (BldgType_2fmCon) set to 0
Feature 105 (BldgType_Twnhs) set to 0
Feature 106 (BldgType_TwnhsE) set to 0
Feature 108 (HouseStyle_1Story) set to 0
Feature 109 (HouseStyle_2.5Fin) set to 0
Feature 112 (HouseStyle_SFoyer) set to 0
Feature 114 (RoofStyle_Gable) set to 0
Feature 115 (RoofStyle_Gambrel) set to 0
Feature 118 (RoofStyle_Shed) set to 0
Feature 120 (RoofMatl_Metal) set to 0
Feature 121 (RoofMatl_Roll) set to 0
Feature 125 (Exterior1st_AsphShn) set to 0
Feature 126 (Exterior1st_BrkComm) set to 0
Feature 128 (Exterior1st_CBlock) set to 0
Feature 130 (Exterior1st_HdBoard) set to 0
Feature 132 (Exterior1st_MetalSd) set to 0
Feature 134 (Exterior1st_Stone) set to 0
Feature 135 (Exterior1st_Stucco) set to 0
Feature 136 (Exterior1st_VinylSd) set to 0
Feature 137 (Exterior1st_Wd Sdng) set to 0
Feature 138 (Exterior1st_WdShing) set to 0
Feature 139 (Exterior2nd_AsphShn) set to 0
Feature 140 (Exterior2nd_Brk Cmn) set to 0
Feature 141 (Exterior2nd_BrkFace) set to 0
Feature 142 (Exterior2nd_CBlock) set to 0
Feature 143 (Exterior2nd_CmentBd) set to 0
Feature 144 (Exterior2nd_HdBoard) set to 0
Feature 146 (Exterior2nd_MetalSd) set to 0
Feature 147 (Exterior2nd_Other) set to 0
Feature 148 (Exterior2nd_Plywood) set to 0
Feature 149 (Exterior2nd_Stone) set to 0
Feature 150 (Exterior2nd_Stucco) set to 0
Feature 152 (Exterior2nd_Wd Sdng) set to 0
Feature 154 (ExterQual_Fa) set to 0
Feature 157 (ExterCond_Fa) set to 0
Feature 158 (ExterCond_Gd) set to 0
Feature 159 (ExterCond_Po) set to 0
Feature 160 (ExterCond_TA) set to 0
Feature 161 (Foundation_CBlock) set to 0
Feature 169 (BsmtCond_Gd) set to 0
Feature 170 (BsmtCond_Po) set to 0
Feature 173 (BsmtExposure_Mn) set to 0
Feature 175 (BsmtFinType1_BLQ) set to 0
Feature 178 (BsmtFinType1_Rec) set to 0
Feature 179 (BsmtFinType1_Unf) set to 0
Feature 180 (BsmtFinType2_BLQ) set to 0
Feature 181 (BsmtFinType2_GLQ) set to 0
Feature 184 (BsmtFinType2_Unf) set to 0
Feature 185 (Heating_GasA) set to 0
Feature 186 (Heating_GasW) set to 0
Feature 187 (Heating_Grav) set to 0
Feature 188 (Heating_OthW) set to 0
Feature 189 (Heating_Wall) set to 0
Feature 190 (HeatingQC_Fa) set to 0
Feature 195 (Electrical_FuseF) set to 0
Feature 196 (Electrical_FuseP) set to 0
Feature 197 (Electrical_Mix) set to 0
Feature 198 (Electrical_SBrkr) set to 0
Feature 204 (Functional_Min2) set to 0
Feature 205 (Functional_Mod) set to 0
Feature 209 (FireplaceQu_Gd) set to 0
Feature 210 (FireplaceQu_Po) set to 0
Feature 211 (FireplaceQu_TA) set to 0
Feature 212 (GarageType_Attchd) set to 0
Feature 213 (GarageType_Basment) set to 0
Feature 215 (GarageType_CarPort) set to 0
Feature 216 (GarageType_Detchd) set to 0
Feature 218 (GarageFinish_Unf) set to 0
Feature 221 (GarageQual_Po) set to 0
Feature 222 (GarageQual_TA) set to 0
Feature 223 (GarageCond_Fa) set to 0
Feature 224 (GarageCond_Gd) set to 0
Feature 225 (GarageCond_Po) set to 0
Feature 226 (GarageCond_TA) set to 0
Feature 229 (SaleType_CWD) set to 0
Feature 230 (SaleType_Con) set to 0
Feature 231 (SaleType_ConLD) set to 0
Feature 232 (SaleType_ConLI) set to 0
Feature 233 (SaleType_ConLw) set to 0
Feature 236 (SaleType_WD) set to 0
Feature 237 (SaleCondition_AdjLand) set to 0
Feature 239 (SaleCondition_Family) set to 0
Feature 241 (SaleCondition_Partial) set to 0
A total of 120 features were set to 0

In [21]:
scoring = {
    "MAE": 'neg_mean_absolute_error',
    "MAPE": 'neg_mean_absolute_percentage_error',
    "MSE": 'neg_mean_squared_error',
    "R2": 'r2'
}

params = {
    "n_estimators": (100, 200, 300, 400),
    "max_depth": (None, 10, 20),
    "max_features": ("sqrt", "log2", None),
}

model = RandomForestRegressor()

grid = GridSearchCV(estimator=model, param_grid=params, scoring=scoring, refit="MAE")

grid.fit(x_train, y_train)

y_pred = grid.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print(f"Random Forests with the final parameters of: ")

for key, value in grid.best_params_.items():
    print(f"{key}: {value}")
metrics.head()

Random Forests with the final parameters of:
max_depth: 20
max_features: sqrt
n_estimators: 400

,Metrics,Values,Explanation
0,Mean Absolute Error,16142.18,Pure error
1,Root Mean Squared Error,22947.66,Penalizes big misses
2,Mean Absolute Percentage Error,0.10,More intepretable MAE
3,R Squared,0.91,Overall fit
4,Adjusted R Squared,0.89,Useful for subset selecting models

In [22]:
import xgboost as xgb

scoring = {
    "MAE": 'neg_mean_absolute_error',
    "MAPE": 'neg_mean_absolute_percentage_error',
    "MSE": 'neg_mean_squared_error',
    "R2": 'r2'
}

params = {
    "n_estimators": (100, 200, 300, 400),
    "max_depth": (3, 6, 9),
    "learning_rate": (0.01, 0.1, 0.5, 1),
    "subsample": (0.33, 0.67, 1)
}

model = xgb.XGBRegressor(tree_method="hist", device="cuda")

grid = GridSearchCV(estimator=model, param_grid=params, scoring=scoring, refit="MAE")

grid.fit(x_train, y_train)

y_pred = grid.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
mape = mean_absolute_percentage_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = create_metrics(mae, rmse, mape, r2)
print(f"XGBoost with the final parameters of: ")

for key, value in grid.best_params_.items():
    print(f"{key}: {value}")
metrics.head()

sh: line 1: nvidia-smi: command not found
/home/jack/Documents/pythonProjects/CS434Project/.venv/lib/python3.13/site-packages/xgboost/core.py:751: UserWarning: [21:09:47] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

XGBoost with the final parameters of:
learning_rate: 0.1
max_depth: 3
n_estimators: 200
subsample: 0.67

,Metrics,Values,Explanation
0,Mean Absolute Error,26818.91,Pure error
1,Root Mean Squared Error,35604.25,Penalizes big misses
2,Mean Absolute Percentage Error,0.14,More intepretable MAE
3,R Squared,0.79,Overall fit
4,Adjusted R Squared,0.74,Useful for subset selecting models

In [23]:
x_lasso = x.drop(columns=dropped)

x_train_lasso, x_test_lasso, y_train_lasso, y_test_lasso = train_test_split(x_lasso, y, random_state=434)
sc = StandardScaler()
x_test_lasso = sc.fit_transform(x_test_lasso)
x_train_lasso = sc.fit_transform(x_train_lasso)

In [24]:
x_train_lasso.shape

(1093, 122)

In [25]:
model = LinearRegression()
model.fit(x_train_lasso, y_train_lasso)
y_pred_lasso = model.predict(x_test_lasso)
mae = mean_absolute_error(y_test_lasso, y_pred_lasso)
mape = mean_absolute_percentage_error(y_test_lasso, y_pred_lasso)
rmse = np.sqrt(mean_squared_error(y_test_lasso, y_pred_lasso))
r2 = r2_score(y_test_lasso, y_pred_lasso)

metrics = create_metrics(mae, rmse, mape, r2)
print("Linear Regression with adjusted parameters from lasso:")
metrics.head()

Linear Regression with adjusted parameters from lasso:

,Metrics,Values,Explanation
0,Mean Absolute Error,17063.14,Pure error
1,Root Mean Squared Error,24117.72,Penalizes big misses
2,Mean Absolute Percentage Error,0.11,More intepretable MAE
3,R Squared,0.90,Overall fit
4,Adjusted R Squared,0.88,Useful for subset selecting models

In [26]:
pipeline3 = Pipeline([
    ('poly', PolynomialFeatures(degree = 3)),
    ('model', LinearRegression())
])

pipeline3.fit(x_train_lasso, y_train_lasso)

y_pred_lasso = pipeline3.predict(x_test_lasso)
mae = mean_absolute_error(y_test_lasso, y_pred_lasso)
mape = mean_absolute_percentage_error(y_test_lasso, y_pred_lasso)
rmse = np.sqrt(mean_squared_error(y_test_lasso, y_pred_lasso))
r2 = r2_score(y_test_lasso, y_pred_lasso)

metrics = create_metrics(mae, rmse, mape, r2)
print("Polynomial Regression with adjusted parameters from lasso (Degree = 3):")
metrics.head()

Polynomial Regression with adjusted parameters from lasso (Degree = 3):

,Metrics,Values,Explanation
0,Mean Absolute Error,21906.69,Pure error
1,Root Mean Squared Error,29645.78,Penalizes big misses
2,Mean Absolute Percentage Error,0.14,More intepretable MAE
3,R Squared,0.85,Overall fit
4,Adjusted R Squared,0.82,Useful for subset selecting models

In [27]:
scoring = {
    "MAE": 'neg_mean_absolute_error',
    "MAPE": 'neg_mean_absolute_percentage_error',
    "MSE": 'neg_mean_squared_error',
    "R2": 'r2'
}

params = {
    "n_estimators": (100, 200, 300, 400),
    "max_depth": (None, 10, 20),
    "max_features": ("sqrt", "log2", None),
}

model = RandomForestRegressor()

grid = GridSearchCV(estimator=model, param_grid=params, scoring=scoring, refit="MAE")

grid.fit(x_train_lasso, y_train_lasso)

y_pred_lasso = grid.predict(x_test_lasso)
mae = mean_absolute_error(y_test_lasso, y_pred_lasso)
mape = mean_absolute_percentage_error(y_test_lasso, y_pred_lasso)
rmse = np.sqrt(mean_squared_error(y_test_lasso, y_pred_lasso))
r2 = r2_score(y_test_lasso, y_pred_lasso)

metrics = create_metrics(mae, rmse, mape, r2)
print(f"Random Forests with adjusted parameters from lasso with the final parameters of: ")

for key, value in grid.best_params_.items():
    print(f"{key}: {value}")
metrics.head()

Random Forests with adjusted parameters from lasso with the final parameters of:
max_depth: 20
max_features: sqrt
n_estimators: 300

,Metrics,Values,Explanation
0,Mean Absolute Error,16057.37,Pure error
1,Root Mean Squared Error,22947.84,Penalizes big misses
2,Mean Absolute Percentage Error,0.10,More intepretable MAE
3,R Squared,0.91,Overall fit
4,Adjusted R Squared,0.89,Useful for subset selecting models